### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by snickler** [corradocavalli/Corcav.Behaviors#15]
I believe we will need UWP support for Corcav.Behaviors. I'm attempting to add a UWP project to my existing Xamarin Forms solution and this is one of the NuGet packages that doesn't support it yet.

Output from VS:

Corcav.Behaviors 2.2.0 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
Corcav.Behaviors 2.2.0 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
Corcav.Behaviors 2.2.0 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
Corcav.Behaviors 2.2.0 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
Corcav.Behaviors 2.2.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Corcav.Behaviors 2.2.0 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
Corcav.Behaviors 2.2.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).

**Comment by DawidSadlik** [comment]
Same problem

**Comment by Robelind** [comment]
Same here.
