### ISSUE TITLE
Cannot install in PCL

### ISSUE THREAD

**Issue by Onjay** [corradocavalli/Corcav.Behaviors#16]
I am trying to follow the below tutorial, but cannot install Corcav.Behaviors in the Xamarin.Forms PCL project. It is installed in the Tutorial's Github Xamarin PCL project, and I've got it installed for Android and UWP, just not in my PCL. I'm getting the error below. Any ideas?

http://blog.qmatteoq.com/prism-for-xamarin-forms-basic-navigation-and-dependency-injection-part-2/

Severity    Code    Description Project File    Line    Suppression State
Error       Could not install package 'Corcav.Behaviors 2.3.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by noahwebster** [comment]
v2.2.0 will work with PCL.

**Comment by corradocavalli** [comment]
Release 2.3.4 fixes it.
