### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pcfountain** [corradocavalli/Corcav.Behaviors#17]
What license does Corcav.Behaviors use?  I cannot find any license information here or on NuGet.

**Comment by corradocavalli** [comment]
No license required, is totally free for you to use.

**Comment by pcfountain** [comment]
Ironically, if there is no license, the code is NOT totally free at all, it's restricted by copyright.  Take a look at these links:

https://blog.codinghorror.com/pick-a-license-any-license/ 
http://softwareengineering.stackexchange.com/questions/311647/what-happens-when-a-software-that-is-open-source-without-any-license-is-later-li

I would strongly encourage you to choose a license.  The MIT license is a nice, open one.  I've found your code to be very useful, and I would like to include it in my current project.  Unfortunately, my company will not allow me to use this library unless the license terms are explicitly declared.

**Comment by pcfountain** [comment]
Hi Corrado,
I just wanted to ask again - please declare a license for this code.  I really like it, and I want to use it.  It's really easy to do, you just have to add a license file to the source - here's a perfect example that can be copy/pasted:
https://bitbucket.org/dadhi/dryioc/src/c1f925c25db2051583034f332406c9e74ec69c8d/LICENSE.txt

I can see that you have a good intent to freely share the code, but in its current state, it is restricted by copyright. I didn't make these rules, but I have to follow them along with everyone else.

Please and Thank You!

**Comment by corradocavalli** [comment]
Hi,
Thanks for the reminder, I've just been busy travelling.
I'll add it this weekend.

Cheers
/C.

On 11 Nov 2016, at 21:28, pcfountain <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Corrado,
I just wanted to ask again - please declare a license for this code. I really like it, and I want to use it. It's really easy to do, you just have to add a license file to the source - here's a perfect example that can be copy/pasted:
https://bitbucket.org/dadhi/dryioc/src/c1f925c25db2051583034f332406c9e74ec69c8d/LICENSE.txt

I can see that you have a good intent to freely share the code, but in its current state, it is restricted by copyright. I didn't make these rules, but I have to follow them along with everyone else.

Please and Thank You!

##

**Comment by corradocavalli** [comment]
MIT license added.

**Comment by pcfountain** [comment]
Awesome, thank you!
