### ISSUE TITLE
Updated Xamarin and Xamarin.Forms and now it's broken :(

### ISSUE THREAD

**Issue by stephenhauck** [corradocavalli/Corcav.Behaviors#19]
I updated to Xamarin 4.2.1.73 today and Xamarin.Forms 2.3.3.175

And now I get this error:
Xamarin.Forms.Xaml.XamlParseException: Position 10:8. Type b:EventToCommand not found in xmlns clr-namespace:Corcav.Behaviors;assembly=Corcav.Behaviors

**Comment by stephenhauck** [comment]
Now I downgraded to Xamarin.Forms 2.3.2.127 and it give me a different error ....


System.IO.FileNotFoundException: Could not load file or assembly 'Corcav.Behaviors' or one of its dependencies

It must be the update they pushed to Visual Studio ....

**Comment by corradocavalli** [comment]
I tried but had no issues. I have updated the package to use latest XF build and removed the use of some API marked as obsolete.
